% Script generated by Brainstorm (12-Apr-2018)

% Input files
sFiles = {...
    'Subject01/sj0011_high_resample/data_S_20_average_170503_1302_time.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Rename event
sFiles = bst_process('CallProcess', 'process_evt_rename', sFiles, [], ...
    'src',  'Correct', ...
    'dest', 'Wrong2');

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

