% Script generated by Brainstorm (12-Apr-2018)

% Input files
sFiles = {...
    'link|Subject01/sj0011_high_resample/results_MN_EEG_KERNEL_180215_2000.mat|Subject01/sj0011_high_resample/data_S_20_average_170503_1302_time.mat', ...
    'link|Subject01/sj0011_high_resample/results_MN_EEG_KERNEL_180215_2001.mat|Subject01/sj0011_high_resample/data_S_20_average_170503_1302_time.mat', ...
    'link|Subject01/sj0011_high_resample/results_MN_EEG_KERNEL_180215_2005.mat|Subject01/sj0011_high_resample/data_S_20_average_170503_1302_time.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Project on default anatomy: surface
sFiles = bst_process('CallProcess', 'process_project_sources', sFiles, [], ...
    'headmodeltype', 'surface');  % Cortex surface

% Process: Spatial smoothing (3.00,abs)
sFiles = bst_process('CallProcess', 'process_ssmooth_surfstat', sFiles, [], ...
    'fwhm',       3, ...
    'overwrite',  1, ...
    'source_abs', 0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

