% Script generated by Brainstorm (08-Jun-2018)

% Input files
sFiles = {...
    'Subject01/@rawsj0011_high/data_0raw_sj0011_high.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: High-pass:0.5Hz
sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
    'sensortypes', 'MEG, EEG', ...
    'highpass',    0.5, ...
    'lowpass',     0, ...
    'attenuation', 'relax', ...  % 40dB (relaxed)
    'mirror',      0, ...
    'useold',      0, ...
    'read_all',    0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

