% Script generated by Brainstorm (08-Feb-2019)

% Input files
% Input files
% Input files
group1 = {...
    'prova_g/sj0012_band/timefreq_concat_190305_2017.mat', ...
    'prova_g/sj0012_band/timefreq_concat_190305_2017.mat'};
group2 = {...
    'prova_g/sj0012_band/timefreq_concat_190305_2017.mat', ...
    'prova_g/sj0012_band/timefreq_concat_190305_2017.mat'};


my_freq_range = [8, 22];


%%%

group_merged = {group1{:}, group2{:}};




for iFile=1:(length(group_merged))
    
    
    %% AT LOOP 1 FROM A REFERENCE FILE CREATE OUTPUT.
    if (iFile == 1)
        
        ref_file1 = bst_process('CallProcess', 'process_extract_values', group_merged{1}, [], ...
            'timewindow', [,], ...
            'freqrange',  [my_freq_range(1), my_freq_range(2)], ...
            'rows',       '', ...
            'isabs',      0, ...
            'avgtime',    0, ...
            'avgrow',     0, ...
            'avgfreq',    1, ...
            'matchrows',  0, ...
            'dim',        1, ...  % 
            'Comment',    '');
        
        
        ref_info = in_bst_data(ref_file1.FileName);
        
        
        n_timepoints = size(ref_info.TF,2);
        n_vertices = size(ref_info.TF,1);
        
        RES_MAT = zeros(n_vertices, n_timepoints, length(group1));
        
        
        
        
        % initialize output
        
        
    end;
    
    
    
    % Process: Extract values: [all]
    curr_file1 = bst_process('CallProcess', 'process_extract_values', group_merged{iFile}, [], ...
            'timewindow', [,], ...
            'freqrange',  [my_freq_range(1), my_freq_range(2)], ...
            'rows',       '', ...
            'isabs',      0, ...
            'avgtime',    0, ...
            'avgrow',     0, ...
            'avgfreq',    0, ...
            'matchrows',  1, ...
            'dim',        1, ...  % 
            'Comment',    '');
        
    
    curr_file_info = in_bst_data(curr_file1.FileName);
    
    % store in the RESMAT the file
    RES_MAT(:,:,iFile) = curr_file_info.TF;
    
    
    
    % Process: Delete selected files
    curr_file = bst_process('CallProcess', 'process_delete', {curr_file1.FileName},[], ...
        'target', 1);  % Delete selected files
    
end


RES_MAT1 = RES_MAT(:,:,1:length(group1));
RES_MAT2 = RES_MAT(:,:,(length(group1)+1):end);


RES_COR = zeros(n_vertices, n_timepoints);
RES_PVAL = zeros(n_vertices, n_timepoints);



% LOOP (it will take about 13 min).
tic
for iVertex = 1:n_vertices
    
    [RES_COR_TEMP, RES_PVAL_TEMP] = corr(squeeze(RES_MAT1(iVertex,:,:))', squeeze(RES_MAT2(iVertex,:,:))');
    RES_COR(iVertex,:) = diag(RES_COR_TEMP);
    RES_PVAL(iVertex,:) = diag(RES_PVAL_TEMP);
    
    
end;
toc



% Initialize output structure
sOutput = db_template('statmat');
sOutput.pmap         = RES_PVAL;
sOutput.tmap         = RES_COR;
sOutput.df           = repmat(length(group_merged)/2, n_vertices, n_timepoints);
sOutput.Correction   = 'no';
sOutput.Type         = 'results';
sOutput.ChannelFlag  = [];
sOutput.Time         = ref_info.Time;
sOutput.ColormapType = 'stat2';
sOutput.DisplayUnits = 't';
sOutput.nComponents  = 1; % NOTA GIORGIO: credo si riferisca a quanti vettori ci sono.
sOutput.GridAtlas    = [];
sOutput.Freqs        = [];
sOutput.TFmask       = [];
sOutput.HeadModelType='surface'
sOutput.SurfaceFile = '@default_subject/tess_cortex_pial_low.mat'
sOutput.Comment = 'Correlation'
sOutput.History = {};



%% 
% Process: Delete selected files
ref_file = bst_process('CallProcess', 'process_delete', ref_file1.FileName ,[], ...
    'target', 1);  % Delete selected files


% % RESHAPE MATRICES TO SPEED UP THE PROCESS
% OUT OF MEMORY
% RES_MAT1_R = reshape(RES_MAT1, [size(RES_MAT1, 1)*size(RES_MAT1, 2), size(RES_MAT1, 3]);
% RES_MAT2_R = reshape(RES_MAT1, [size(RES_MAT2, 1)*size(RES_MAT2, 2), size(RES_MAT2, 3]);
%
% [RES_COR_TEMP, RES_PVAL_TEMP] = cov(RES_MAT1_R', RES_MAT2_R');
%
